### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by bommezijn** [cmda-bt/pt-course-19-20#188]
# Job Story + static site

## Name
Nathan Bommezijn

## Class
TECH-4

## GitHub username
[Dewarian](https://github.com/dewarian/)
[Dating static page](https://dewarian.github.io/bt-dating-app/)

## Job story
**When I just signed in the dating app, I want to see the people that fit my preferences, So I can join the meat market and find my potential match or possibly something more.**

**Comment by TuriGuilano** [comment]
Hi Nathan, this job story gives you a very broad way of interpretation; on which part would you like to lay an emphasis? Make it more specific - say; "I want to be able to create a selection based on cooking preferences".. This way you make it more clear in which direction you'll be heading.

With respect to your code - I can't really give feedback since there isn't too much html!
