### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by victorboucher** [cmda-bt/pt-course-19-20#209]
# Job Story + stagic site

## Name
Victor Boucher

## Class
tech-4

## GitHub username
[Profile page](https://github.com/BVictorB)
[Live version](https://bvictorb.github.io/cmd-dating-app/)

## Job story
As a user I want to be able to register directly from the login page when I do not have an account.

**Comment by TuriGuilano** [comment]
Hi Victor, you defined a user story instead of a job story. Please consult this article to get a better understanding of the differences: https://jtbd.info/replacing-the-user-story-with-the-job-story-af7cdee10c27

An example job story could be: 

_When im sitting at home wondering why I am still alone and have not yet found a partner, I want to be able to quickly create an account at a dating platform so I can finally meet the individual that I want to share my life with.._

Your feature however is already looking nice!
