### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by saskiapool** [cmda-bt/pt-course-19-20#231]
# Job Story + static site

## Name
Saskia

## Class
Tech-4

## GitHub username
https://github.com/saskiapool/dating-app-feature
Voor meer hw zie [wiki](https://github.com/saskiapool/dating-app-feature/wiki/Project-tech-huiswerk)

## Job story
Dutch:
Wanneer ik de liefde wil vinden, wil ik gematcht worden op restaurant smaak, zodat ik met mijn toekomstige vriend/vriendin uit eten kan.

English:
When I want to find love, I want to be matched on my taste of restaurant, so I can go out to diner together with my loved one and have diner in my favorite restaurant.

**Comment by TuriGuilano** [comment]
Hi Saskia, please write the job story in English - when you have done so please let me know then I can look at the strucutre!

With respect to your code - there is no need to upload a .zip file, you can upload your files as they are. If you have struggles in doing so, do let me know. Then I can walk you through the process. For now, on DLO you can find an instructional video of Github and Git (under the course Project Tech - content tab). 

Can you upload the files instead of a .zip and inform me? Then I can look at your code.
